###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################


arch:
  - amd64
  - ppc64le
  - s390x

clusterLifecycle:
  name: rcm
  replicaCount: 1
  image:
    repository: quay.io/open-cluster-management
    name: mcm-rcm-api
    tag: 1.0.0
    pullPolicy: Always
    pullSecret: null
  resources:
    requests:
      memory: "96Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"
    nodeSelector:
      master: "true"
  controller:
    defaultPullSecret: infra-registry-key
    defaultRepository: ""

imageTagPostfix: ""

auditService:
  image:
    repository: quay.io/open-cluster-management
    name: icp-audit-service
    tag: 3.3.1
    pullPolicy: Always
  resources:
    requests:
      memory: "64Mi"
      cpu: "25m"
    limits:
      memory: "512Mi"
      cpu: "100m"
  config:
    enabled: true
    auditEnabled: false
    journalPath: /run/systemd/journal
    auditLogPath: /var/log/audit
    logrotate: |-
      /var/log/audit/*.log {
        su root root
        copytruncate
        rotate 24
        hourly
        missingok
        notifempty
      }
    logrotateConf: |-
      include /etc/logrotate.d

clusterController:
  name: rcm-cluster-controller
  replicaCount: 1
  image:
    repository: quay.io/open-cluster-management
    name: multicloud-operators-cluster-controller
    tag: 1.0.0
    pullPolicy: Always
    pullSecret: null
  resources:
    requests:
      memory: "96Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"
    nodeSelector:
      master: "true"
