###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################


arch:
  - amd64
  - ppc64le
  - s390x

clusterController:
  name: rcm-controller
  replicaCount: 1
  resources:
    requests:
      memory: "96Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"

hubconfig:
  nodeSelector: null

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
          - amd64
          - ppc64le
          - s390x
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 70
      podAffinityTerm:
        topologyKey: failure-domain.beta.kubernetes.io/zone
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - rcm-controller
    - weight: 35
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - rcm-controller

global: 
  imagePullPolicy: Always 
  imagePullSecret: null
  imageRepository: "quay.io/open-cluster-management"
  imageTagPostfix: ""
  imageOverrides: 
    rcm_controller: "quay.io/open-cluster-management/rcm-controller:1.0.0"
    klusterlet_operator: "quay.io/open-cluster-management/klusterlet-operator:1.0.0"