###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2018, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

## Metadata for cluster lifecycle management configuration
## This metadata is used to drive configuration of the Helm chart installation


arch:
  __metadata:
    name: "Architecture"
    label: "Architecture scheduling preference"
    description: "Architecture scheduling preference for worker node"
    immutable: true
    required: true
    hidden: true
    options:
      - label: "amd64"
        value: "amd64"
      - label: "ppc64le"
        value: "ppc64le"
      - label: "s390x"
        value: "s390x"

clusterController:
  name:
    __metadata:
      label: "Cluster lifecycle container name"
      description: "Container name for Cluster lifecycle controller"
      type: "string"
      immutable: false
      required: false
  replicaCount:
    __metadata:
      label: "Cluster lifecycle pod replica count"
      description: "replica count for Cluster lifecycle controller pod"
      type: "number"
      immutable: false
      required: false
  resources:
    requests:
      memory:
        __metadata:
          label: "Memory request"
          description: "Resource request of memory"
          type: "string"
          immutable: false
          required: false
      cpu:
        __metadata:
          label: "CPU request"
          description: "Resource request of CPU"
          type: "string"
          immutable: false
          required: false
    limits:
      memory:
        __metadata:
          label: "Memory limit"
          description: "Resource limit of memory"
          type: "string"
          immutable: false
          required: false
      cpu:
        __metadata:
          label: "CPU limit"
          description: "Resource limit of CPU"
          type: "string"
          immutable: false
          required: false
  import:
    name:
      __metadata:
      label: "Cluster controller configmap name"
      description: "Configmap name for Cluster controller"
      type: "string"
      immutable: false
      required: false

global:
  imagePullPolicy:
    __metadata:
      label: "Cluster lifecycle controller Image Pull Policy"
      description:  "Image Pull Policy for Cluster lifecycle controller"
      type: "string"
      required: false
      options:
      - label: "IfNotPresent"
        value: "IfNotPresent"
      - label: "Always"
        value: "Always"
      - label: "Never"
        value: "Never"
  imagePullSecret:
    __metadata:
      label: "Cluster lifecycle controller api Image PullSecret"
      description: "Image PullSecret Repository for Cluster lifecycle controller"
      type: "string"
      immutable: false
      required: false
  imageRepository:
    __metadata:
      label: "Cluster lifecycle controller api Image Repository"
      description: "Image Repository for Cluster lifecycle controller"
      type: "string"
      immutable: false
      required: false
  imageTagPostfix:
    __metadata:
      label: "Cluster lifecycle controller api Image Tag Postfix"
      description: "Image Tag Postfix for Cluster lifecycle controller"
      type: "string"
      immutable: false
      required: false
  imageOverrides:
    __metadata:
    name: "imageOverrides"
    label: "Image Overrides"
    description: "Image Overrides"
    rcm_controller:
      __metadata:
        name: "rcm_controller"
        label: "rcm_controller"
        description: "Image override for rcm-controller"
        type: "string"
        immutable: false
        required: false
    endpoint_operator:
      __metadata:
        name: "endpoint_operator"
        label: "endpoint_operator"
        description: "Image override for endpoint-operator"
        type: "string"
        immutable: false
        required: false