language: minimal

# Only build on master, stable branches and tag
# The stable branch and tag should be leading with numbers
branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

stages:
  - build
  - release-ff

jobs:
  include:
    - stage: build
      name: "Build the Helm chart"
      before_script:
        - git config --global url."git@github.com:".insteadOf "https://github.com"
        - make
        - make tool
        - make lint
      script:
        - make build
    - stage: release-ff
      name: "Push commits to current release branch"
      if: type = push AND branch =~ /^master$/
      script:
        - make
        - make release-ff

