language: minimal

# Only build on master, stable branches and tag
# The stable branch and tag should be leading with numbers
branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

stages:
  - build
  - release-ff
  - auto

jobs:
  include:
    - stage: build
      name: "Build the Helm chart"
      before_script:
        - git config --global url."git@github.com:".insteadOf "https://github.com"
        - make tool
        - make lint
      script:
        - make build
    - stage: release-ff
      name: "Push commits to current release branch"
      if: type = push AND branch =~ /^master$/
      script:
        - make
        - make release-ff
    - stage: auto
      name: "Auto trigger mch-repo"
      if: type = push AND branch =~ /^master$/
      script: 
        - git clone --single-branch --branch master https://${MCH_REPO_BOT_TOKEN}@github.com/open-cluster-management/multicloudhub-repo.git
        - cd multicloudhub-repo
        - ./cicd-scripts/chartAutomation.sh rcm-chart

