###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2018, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.clusterController.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.clusterController.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.clusterController.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.clusterController.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  minReadySeconds: 0
  replicas: {{ .Values.clusterController.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.clusterController.name }}
      component: {{ .Values.clusterController.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.clusterController.name }}
        component: {{ .Values.clusterController.name }}
        release: {{ .Release.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        heritage: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ .Values.clusterController.name }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      annotations:
        productName: "IBM Multi-Cloud Manager"
        productID: "product-id"
        productVersion: 1.0.0
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
    {{- if .Values.clusterController.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.clusterController.image.pullSecret }}
    {{- end }}
      serviceAccountName: {{ .Values.clusterController.name }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsNonRoot: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                {{- range .Values.arch }}
                - {{ . }}
                {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ .Values.clusterController.name }}
              topologyKey: failure-domain.beta.kubernetes.io/zone
      tolerations:
        - key: dedicated
          operator: Exists
          effect: NoSchedule
      containers:
      - name: cluster-controller
        image: "{{ .Values.clusterController.image.repository}}/{{.Values.clusterController.image.name}}:{{ .Values.clusterController.image.tag }}{{ .Values.imageTagPostfix }}"
        imagePullPolicy: {{ .Values.clusterController.image.pullPolicy }}
        resources:
{{ toYaml .Values.clusterController.resources | indent 10 }}
        env:
          - name: WATCH_NAMESPACE
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: {{ .Values.clusterController.name }}
          - name: IMAGE_TAG_POSTFIX
            value: {{ .Values.imageTagPostfix }}
          - name: DEFAULT_IMAGE_PULL_SECRET
            value: {{ .Values.imagePullSecret }}
          - name: DEFAULT_IMAGE_REGISTRY
            value: {{ .Values.imageRepository }}
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
    {{- if .Values.clusterController.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.clusterController.nodeSelector | indent 8 }}
    {{- end }}
