kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.clusterLifecycle.import.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.clusterLifecycle.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.clusterLifecycle.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.clusterLifecycle.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    config: {{ .Values.clusterLifecycle.import.name }}
data:
  ## Cluster Configurations
  clusterName: "cluster-name"
  clusterNamespace: "cluster-namespace"

  clusterLabels:
    cloud: "auto-detect"
    vendor: "auto-detect"
    # environment: "Dev"
    # region: "US"

  # Configure application management feature
  applicationManager:
    enabled: true

  # Configure monitoring for metric collection
  prometheusIntegration:
    enabled: true

  # Configure gathering of cluster topology data
  topologyCollector:
    enabled: true
    updateInterval: 15

  # Configure indexing for multicluster search feature
  searchCollector:
    enabled: true

  # Configure multicluster GRC policy feature
  policyController:
    enabled: true

  # Configure multicluster service registry feature
  serviceRegistry:
    enabled: true
    dnsSuffix: "mcm.svc"
    plugins: "kube-service"

  ## Image Registry Configurations
  # private_registry_enabled: false
  # docker_username:
  # docker_password:
  # imageRegistry:
  # imageNamePostfix: