###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2018, 2019 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterLifecycle.name }}
  labels:
    app: {{ .Values.clusterLifecycle.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.clusterLifecycle.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  ports:
    - port: 8060
      targetPort: 8060
  selector:
    app: {{ .Values.clusterLifecycle.name }}
    release: {{ .Release.Name }}
