apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: klusterlet-addon-controller-validating-webhook
  annotations:
    certmanager.k8s.io/inject-ca-from: "{{ .Release.Namespace }}/{{ .Values.klusterletAddonWebhook.certName }}"
  labels:
    app: {{ .Values.klusterletAddonController.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
webhooks:
- name: klusterletaddonconfig.validating-webhook.open-cluster-management.io
  failurePolicy: Fail
  clientConfig:
    service:
      # reach the webhook via the registered aggregated API
      namespace: {{ .Release.Namespace | quote }}
      name: {{ .Values.klusterletAddonWebhook.name }}
      path: /validate-v1-klusterletaddonconfig
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - agent.open-cluster-management.io
    apiVersions:
    - "*"
    resources:
    - klusterletaddonconfigs
    scope:     "Namespaced"
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
