
# Create a selfsigned Issuer, in order to create a root CA certificate for RHACM
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: klusterlet-addon-rhacm-selfsign
  namespace: "{{ .Release.Namespace }}"
spec:
  selfSigned: {}