apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.klusterletAddonWebhook.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Values.klusterletAddonController.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 6443
  selector:
    app: {{ .Values.klusterletAddonController.name }}
    release: {{ .Release.Name }}
