# Copyright Contributors to the Open Cluster Management project

###############################################################################
# Licensed Materials - Property of IBM
# (C) Copyright IBM Corporation 2020 All Rights Reserved
# US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
###############################################################################
# Copyright (c) 2020 Red Hat, Inc

org: open-cluster-management

arch:
  - amd64
  - ppc64le
  - s390x

clusterController:
  name: managedcluster-import-controller
  resources:
    requests:
      memory: "96Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"

hubconfig:
  nodeSelector: null
  replicaCount: 2

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
          - amd64
          - ppc64le
          - s390x
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 70
      podAffinityTerm:
        topologyKey: topology.kubernetes.io/zone
        labelSelector:
          matchExpressions:
          - key: ocm-antiaffinity-selector
            operator: In
            values:
            - managedclusterimport
    - weight: 35
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
          - key: ocm-antiaffinity-selector
            operator: In
            values:
            - managedclusterimport

klusterletAddonController:
  name: klusterlet-addon-controller
  resources:
    requests:
      memory: "96Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "500m"

klusterletAddonControllerAffinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
          - amd64
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 70
      podAffinityTerm:
        topologyKey: topology.kubernetes.io/zone
        labelSelector:
          matchExpressions:
          - key: ocm-antiaffinity-selector
            operator: In
            values:
            - klusterletaddon
    - weight: 35
      podAffinityTerm:
        topologyKey: kubernetes.io/hostname
        labelSelector:
          matchExpressions:
          - key: ocm-antiaffinity-selector
            operator: In
            values:
            - klusterletaddon

klusterletAddonWebhook:
  name: klusterlet-addon-webhook
  secretName: klusterlet-addon-webhook-tls
  certName: klusterlet-addon-webhook-cert

clusterlifecycleStateMetrics:
  name: clusterlifecycle-state-metrics
  resources:
    requests:
      memory: "32Mi"
      cpu: "25m"
    limits:
      memory: "256Mi"
      cpu: "500m"

global: 
  useShaManifest: true
  imagePullPolicy: IfNotPresent 
  imagePullSecret: null
  imageRepository: "quay.io/open-cluster-management"
  imageTagPostfix: ""
  imageOverrides: 
    rcm_controller: "quay.io/open-cluster-management/rcm-controller:2.1.0"
    registration_operator: "quay.io/open-cluster-management/registration-operator:0.0.1"
    registration: "quay.io/open-cluster-management/registration:0.0.1"
    work: "quay.io/open-cluster-management/work:0.0.1"
    endpoint_operator: "quay.io/open-cluster-management/endpoint-operator:2.1.0"
    clusterlifecycle_state_metrics: "quay.io/open-cluster-management/clusterlifecycle-state-metrics:2.2.0"
