# Copyright Contributors to the Open Cluster Management project
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.org }}.{{ .Release.Name }}.{{ .Values.ClusterClaimsController.shortName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.ClusterClaimsController.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.ClusterClaimsController.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.ClusterClaimsController.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
subjects:
- kind: ServiceAccount
  name: {{ .Values.ClusterClaimsController.shortName }}
  namespace: {{ .Release.Namespace }}           ## CHANGE: ACM namespace
roleRef:
  kind: ClusterRole
  name: {{ .Values.org }}.{{ .Release.Name }}.{{ .Values.ClusterClaimsController.shortName }}
  apiGroup: rbac.authorization.k8s.io
