---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.org }}.{{ .Release.Name }}.{{ .Values.ClusterCuratorController.shortName }}
  labels:
    app: {{ .Values.ClusterCuratorController.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.ClusterCuratorController.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.ClusterCuratorController.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
rules:
# New Rules added to ClusterInstaller
# Leader Lock requires configmaps(create&get) and pods(get)
- apiGroups: ["tower.ansible.com","batch",""]
  resources: ["ansiblejobs","jobs","serviceaccounts","configmaps"]
  verbs: ["create","get"]

- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles","rolebindings"]
  verbs: ["create","get"]

- apiGroups: ["", "hive.openshift.io"]
  resources: ["configmaps", "clusterdeployments"]
  verbs: ["patch"]

- apiGroups: ["internal.open-cluster-management.io",""]
  resources: ["managedclusterinfos","pods"]
  verbs: ["get"]

# Specific to the controller only
- apiGroups: ["cluster.open-cluster-management.io"] 
  resources: ["managedclusters"]
  verbs: ["watch","list"]