# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:addons:{{ .Values.klusterletAddonController.addons.search.name }}
rules:
- verbs:
  - create
  apiGroups:
  - proxy.open-cluster-management.io
  resources:
  - clusterstatuses/aggregator
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  resourceNames:
  - {{ .Values.klusterletAddonController.addons.search.name }}
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create