# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterlifecycleStateMetrics.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    clc-app: {{ .Values.clusterlifecycleStateMetrics.name }}
    app: {{ .Values.clusterlifecycleStateMetrics.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.clusterlifecycleStateMetrics.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.clusterlifecycleStateMetrics.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Values.clusterlifecycleStateMetrics.name }}-certs
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 8443
    targetPort: 8443
  selector:
    app: {{ .Values.clusterlifecycleStateMetrics.name }}