# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.org }}:{{ .Release.Name }}:{{ .Values.clusterlifecycleStateMetrics.name }}-prometheus-v2
  labels:
    app: {{ .Values.clusterlifecycleStateMetrics.name }}-v2
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.clusterlifecycleStateMetrics.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.clusterlifecycleStateMetrics.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.org }}:{{ .Release.Name }}:{{ .Values.clusterlifecycleStateMetrics.name }}-v2
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
