# Copyright Contributors to the Open Cluster Management project
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ProviderCredentialController.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.ProviderCredentialController.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.ProviderCredentialController.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.ProviderCredentialController.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.ProviderCredentialController.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.ProviderCredentialController.name }}
    spec:
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      {{- with .Values.providerCredentialAffinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      tolerations:
      - key: dedicated
        operator: Exists
        effect: NoSchedule
      - effect: NoSchedule 
        key: node-role.kubernetes.io/infra 
        operator: Exists

      serviceAccountName: {{ .Values.ProviderCredentialController.shortName }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true

      containers:
      - command:
        - "./manager"
        - "-enable-leader-election"
        image: "{{ .Values.global.imageOverrides.provider_credential_controller }}"
        imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
        name: {{ .Values.ProviderCredentialController.name }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        resources:
{{ toYaml .Values.ProviderCredentialController.resources | indent 10 }}
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}

